Fix bug in TaskDefinitionLoader for specification of aws sdk. It's require symbolized keys at any level of parameters.
e.g.)
> ArgumentError: parameter validator found 2 errors:
  - missing required parameter params[:container_definitions][0]["log_configuration"][:log_driver]
  - missing required parameter params[:container_definitions][1]["log_configuration"][:log_driver]